### ISSUE TITLE
"latest" release hasn't been updated since June

### ISSUE THREAD

**Issue by jamespollard8** [vmware-tanzu/dependency-labeler#44]
1) we're starting to use this in a cf-for-k8s pipeline (to deplab annotate eirini) - yay 🎉 

2) we're auto using the latest github release and we released the latest hasn't been updated in quite some time
![image](https://user-images.githubusercontent.com/47124749/94499257-6fba7400-01b9-11eb-8c3e-d3b37f4b8045.png)

- James, from Release Integration

**Comment by xtreme-shane-lattanzio** [comment]
Hi @jamespollard8 ! We haven't made many changes except dependency bumps in the last little while as well as preparing the repo for open source. Is there something you are looking for specifically to be released? We can make one for sure but just didn't have a reason to. We haven't had much time to make enhancements which is another reason why we wanted to make this open source.

**Comment by jamespollard8** [comment]
> Is there something you are looking for specifically to be released?

Nope, nothing in particular. It just seemed like a "smell" that there haven't been any releases in several months.

Thanks for your response - I'll close this out as it seems not actionable for y'all.
